--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-11-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTENDANCE
--------------------------------------------------------

  CREATE TABLE "BITCAMP"."ATTENDANCE" 
   (	"A_IDX" NUMBER(20,0), 
	"A_TITLE" VARCHAR2(50 BYTE), 
	"A_CONTENT" CLOB, 
	"A_TYPE" VARCHAR2(20 BYTE), 
	"A_WRITER" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(30 BYTE), 
	"WRITE_DATE" DATE DEFAULT SYSDATE, 
	"MOD_DATE" DATE DEFAULT SYSDATE, 
	"ORI_NAME" VARCHAR2(50 BYTE), 
	"AVAILABLE" NUMBER(20,0) DEFAULT 1, 
	"STATUS" NUMBER(20,0) DEFAULT 0, 
	"FILE_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("A_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."A_IDX" IS '출첵 인덱스';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."A_TITLE" IS '글 제목';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."A_CONTENT" IS '글 내용';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."A_TYPE" IS '결석 사유';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."A_WRITER" IS '글쓴이';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."USER_ID" IS '글쓴이 ID';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."WRITE_DATE" IS '작성일';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."MOD_DATE" IS '수정일';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."ORI_NAME" IS '파일 원본 이름';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."AVAILABLE" IS '삭제 처리';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."STATUS" IS '확인 상태';
   COMMENT ON COLUMN "BITCAMP"."ATTENDANCE"."FILE_NAME" IS '업로드 파일 이름 ';
REM INSERTING into BITCAMP.ATTENDANCE
SET DEFINE OFF;
Insert into BITCAMP.ATTENDANCE (A_IDX,A_TITLE,A_TYPE,A_WRITER,USER_ID,WRITE_DATE,MOD_DATE,ORI_NAME,AVAILABLE,STATUS,FILE_NAME) values (5,'탁구입니다.','조퇴','탁구','kimtolkong',to_date('21/06/05','RR/MM/DD'),to_date('21/06/05','RR/MM/DD'),'탁구 사진.jpg',1,1,'나는 김탁구다');

--------------------------------------------------------
--  DDL for Index ATTENDANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITCAMP"."ATTENDANCE_PK" ON "BITCAMP"."ATTENDANCE" ("A_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "BITCAMP"."ATTENDANCE" MODIFY ("A_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BITCAMP"."ATTENDANCE" MODIFY ("A_TITLE" NOT NULL ENABLE);
  ALTER TABLE "BITCAMP"."ATTENDANCE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BITCAMP"."ATTENDANCE" ADD CONSTRAINT "ATTENDANCE_PK" PRIMARY KEY ("A_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITCAMP"."ATTENDANCE" MODIFY ("AVAILABLE" NOT NULL ENABLE);
  ALTER TABLE "BITCAMP"."ATTENDANCE" MODIFY ("A_IDX" NOT NULL ENABLE);
