--PROJECT 비트 공지사항 게시판

--비트 공지사항 게시글(BIT_T)
CREATE TABLE BIT_T (
	B_IDX NUMBER CONSTRAINT BIT_T_PK PRIMARY KEY, --글번호
	SUBJECT VARCHAR2(50), --글제목
	WRITER VARCHAR2(20), --작성자
    CONTENT CLOB, --글내용
    FILE_NAME VARCHAR2(50), --저장되는 파일명
	ORI_NAME VARCHAR2(50), --원본 파일명
    PWD VARCHAR2(20), --암호
    WRITE_DATE DATE DEFAULT SYSDATE, --작성일자
    EDITE_DATE DATE DEFAULT SYSDATE, --수정일자
    IP VARCHAR2(15), --작성자 IP주소
    HIT NUMBER(4) --조회수
);

--게시글에 대한 댓글(COMMENT_T)
CREATE TABLE COMMENT_T (
	C_IDX NUMBER(6) CONSTRAINT COMM_T_PK PRIMARY KEY, --댓글의 고유번호,기본키
	WRITER VARCHAR2(20),--댓글작성자
	CONTENT CLOB, --댓글내용
	PWD VARCHAR2(20), --댓글작성자의 비밀번호
	WRITE_DATE DATE DEFAULT SYSDATE, --댓글작성 날짜3
	IP VARCHAR2(15), --댓글작성자 IP주소
    B_IDX NUMBER(6), --게시글(원글)의 번호
	CONSTRAINT COMM_T_FK FOREIGN KEY (B_IDX) REFERENCES BIT_T(B_IDX)
    --BIT_T의 (B_IDX)값이 변경되면 COMMENT_T의 (B_IDX)값도 같이 변경되게 함
);

--시퀀스 추가
CREATE SEQUENCE BIT_T_SEQ NOCACHE;
CREATE SEQUENCE COMMENT_T_SEQ NOCACHE;
--------------------------------------------
--글 목록 조회를 위한 샘플 데이타 작성
INSERT INTO BIT_T
VALUES (BIT_T_SEQ.NEXTVAL, '테스트1','테스터','테스트1-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
INSERT INTO BIT_T 
VALUES (BIT_T_SEQ.NEXTVAL, '테스트2','테스터','테스트2-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
INSERT INTO BIT_T 
VALUES (BIT_T_SEQ.NEXTVAL, '테스트3','테스터','테스트3-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
INSERT INTO BIT_T 
VALUES (BIT_T_SEQ.NEXTVAL, '테스트4','테스터','테스트4-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
INSERT INTO BIT_T 
VALUES (BIT_T_SEQ.NEXTVAL, '테스트5','테스터','테스트5-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
INSERT INTO BIT_T 
VALUES (BIT_T_SEQ.NEXTVAL, '테스트6','테스터','테스트6-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
INSERT INTO BIT_T 
VALUES (BBS_T_SEQ.NEXTVAL, '테스트7','테스터','테스트7-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
INSERT INTO BIT_T 
VALUES (BIT_T_SEQ.NEXTVAL, '테스트8','테스터','테스트8-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
INSERT INTO BIT_T 
VALUES (BIT_T_SEQ.NEXTVAL, '테스트9','테스터','테스트9-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
INSERT INTO BIT_T 
VALUES (BIT_T_SEQ.NEXTVAL, '테스트10','테스터','테스트10-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
INSERT INTO BIT_T 
VALUES (BIT_T_SEQ.NEXTVAL, '테스트11','테스터','테스트11-내용','','','1234',SYSDATE,SYSDATE,'127.0.0.1',0);
--------------------
--댓글 샘플 데이타 작성
INSERT INTO COMMENT_T
VALUES (COMMENT_T_SEQ.NEXTVAL, 'C테스터', 'C-내용1',
        '1234', SYSDATE, '127.0.0.1', 10);
INSERT INTO COMMENT_T
VALUES (COMMENT_T_SEQ.NEXTVAL, 'C테스터', 'C-내용2',
        '1234', SYSDATE, '127.0.0.1', 10); 
INSERT INTO COMMENT_T
VALUES (COMMENT_T_SEQ.NEXTVAL, 'C테스터', 'C-내용3',
        '1234', SYSDATE, '127.0.0.1', 10); 

----------------------------------------
SELECT * FROM BIT_T;
SELECT * FROM COMMENT_T;

COMMIT;